server:
  port: 8081

spring:
  datasource:
    name: postgres-db-name
    url: jdbc:postgresql://localhost:5432/compose-postgres
    username: root
    password: postgresDB
    driver-class-name: org.postgresql.Driver


